### ISSUE TITLE
[FE][Taski] Stworzyć milestone dla Pojedynczej grupy

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#57]
## Informacje
Stworzyć milestone, który będzie posiadał taski związane ze stworzeniem kompletnego widoku pojedynczej grupy

### Kryteria akceptacji
- [x] Task obejmujący podstawową stronę pojedynczej grupy z listą eventów
- [x] Task obejmujący stworzenie części z członkami grupy
- [x] task obejmujący przejście do listy członków po kliknięciu w "zobacz więcej"
- [x] Task obejmujący stronę z listą członków
