### ISSUE TITLE
[FE][Taski] Stworzyć milestone dla Admina

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#58]
### Informacje
Stworzyć milestone, który będzie posiadał taski związane ze stworzeniem kmpletnej funkcjonalności Admina

### Kryteria akceptacji
- [ ] Stworzyć task dla komponentu propozycji kategorii
- [ ] Stworzyć task dla listy propozycji kategorii
- [ ] Stworzyć task dla funkcjonalności przyjmowania bądź odrzucania propozycji kategorii
- [ ] Stworzyć task dla edytowania kategorii
- [ ] Stworzyć task dla komponentu kategorii
- [ ] Stworzyć task dla listy kategorii
- [ ] Stworzyć task dla funkcjonalności dezaktywacji kategorii
- [ ] Stworzyć task dla edytowania kategorii
- [ ] Stworzyć task dla dodawania nowej kategorii
- [ ] Stworzyć task dla komponentu hashtagu
- [ ] Stworzyć task dla listy hashtagów
- [ ] Stworzyć task dla dezaktywacji hashtagu
