### ISSUE TITLE
[FE][U]Wyświetlanie ankiet

### ISSUE THREAD

**Issue by annkierl** [akademia-envelo-3/moovelo-front#96]
### Story
Użytkownik widzi ankietę w wydarzeniu.
### Cel:
Celem zadania jest wyświetlenie użytkownikowi ankiety. Na tym etapie nie implementujemy wysyłania wyboru użytkownika.
### Makieta
ankieta niewypełniona: 
https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613030%3A7950&t=5dpFPyjKVJEba0Lu-0
###Task Powiązany:
- #48 
- #9 
- ### Endpointy: 
GET events/{eventId}/surveys

```
  "eventSurveys": [
    {
      "question": "test",
      "isMultipleChoice": true,
      "answers": [
        {
          "id": 1,
          "value": "",
          "voted": 20
        }
      ],
      "yourAnswersIds": [
     {
         "id": 1
      }
     ]
    }
  ]
}

```
### Kryteria akceptacji:
- [x] Należy stworzyć osobny komponent ankiety i dodać go do templatki eventu.
- [x] Należy wyświetlić ankietę wg designu figmy.

**Comment by JRRBorkowski** [comment]
@PawelJurga do sprawdzenia

[Preview](https://feature-96-wyswietlanie-ankiet--moovelo-envelo.netlify.app/theme)

Baza danych:
```
 {
 "eventSurveys": [
    {
      "question": "Mięso?",
      "isMultipleChoice": false,
      "answers": [
        {
          "id": 1,
          "value": "Tak",
          "voted": 20
        },
        {
          "id": 2,
          "value": "Nie",
          "voted": 10
        },
        {
          "id": 3,
          "value": "Bardzo nie",
          "voted": 2
        }
      ],
      "yourAnswersIds": []
    },
    {
      "question": "Kotlet?",
      "isMultipleChoice": true,
      "answers": [
        {
          "id": 1,
          "value": "Tak",
          "voted": 20
        },
        {
          "id": 2,
          "value": "Nie",
          "voted": 10
        },
        {
          "id": 3,
          "value": "Bardzo nie",
          "voted": 2
        }
      ],
      "yourAnswersIds": []
    }
  ]
}
```

**Comment by PawelJurga** [comment]
@JRRBorkowski 
 - [x] Należy stworzyć osobny komponent ankiety i dodać go do templatki eventu.

- [x] Należy wyświetlić ankietę wg designu figmy.
**Nie mam uwag do komponentu, a jedynie zapytanie. W przypadku ankiety "Kotlet ?" można zaznaczyć wszystkie checkboxy, czy tak** **ma być ?. Mam też sugestię, aby wykorzystać w aplikacji kwadratowe checkboxy - jakoś lepiej wyglądają :)**

**Comment by JRRBorkowski** [comment]
Checkbox oznacza ankietę wielokrotnego wyboru, kółko pojedynczego. Uznaliśmy, że to dobrze pokazuje różnicę pomiędzy nimi.

**Comment by PawelJurga** [comment]
**W związku z powyższym 
Rekomenduję zakończenie taska :)**
